### ISSUE TITLE
Curve support

### ISSUE THREAD

**Issue by dupes** [nebland/dnp3-simulator#16]
* [x] managing curve referenced bit (set to true if selected curve is referenced, false if not)
* [x] don't allow curve to be referenced (can't be referenced from multiple modes)
* [x] initialize each mode to a (empty) curve
* [x] set curve pool to 20
* [x] can't update curve if curve is referenced and enabled
* [ ] If an invalid curve is selected, return parameter_error IIN
  * Can we set the IIN bits in the simulator?

**Comment by acdupont** [comment]
The curve indexes are being left at 0
