### ISSUE TITLE
Support sparse data points

### ISSUE THREAD

**Issue by dupes** [nebland/dnp3-simulator#21]
See the discussion here for how to use a sparse setup:
https://groups.google.com/forum/#!msg/automatak-dnp3/P6eA_M8vkBg/Yapp0q_tAQAJ
* [x] Update python script to add *enable* field to indexes-config.json for enabling/disabling point
* [x] Update DatabaseTemplate using the *enable* field, setting config.databaseTemplate.analogOutputStatii[index].index value in both for loops https://github.com/nebland/dnp3-simulator/blob/3bc18cf9bafb92e57b1f0f150c0ba7b97aef8480/simulator/DNP3/DEROutstationPlugin/OutstationInstance.cs#L57
* [x] Update other collections to look at points in map rather than number of points to determine OUT_OF_RANGE https://github.com/nebland/dnp3-simulator/blob/3bc18cf9bafb92e57b1f0f150c0ba7b97aef8480/simulator/DNP3/DEROutstationPlugin/OutstationForm.cs#L367

**Comment by acdupont** [comment]
sparse data points discussion in google group:
https://groups.google.com/forum/#!msg/automatak-dnp3/P6eA_M8vkBg/Yapp0q_tAQAJ
